/**
 * Single source of truth for event-type → severity mapping.
 *
 * Every notification INSERT site reads getSeverity() from here.
 * Add future event types in SEVERITY_MAP — nothing else needs changing.
 * Safe to import in both server and client code (no side effects).
 */

export type Severity    = 'low' | 'medium' | 'high' | 'critical';
export type AlertStatus = 'new' | 'acknowledged' | 'resolved';

// ── Severity mapping ───────────────────────────────────────────────────────

export const SEVERITY_MAP: Record<string, Severity> = {
  // patient-side events (generated by the app today)
  reminder_done:      'low',
  reminder_missed:    'medium',
  sos:                'critical',
  left_zone:          'high',
  inactivity:         'high',
  companion_question: 'low',
  // future events — add here when built
  // fall_detected:   'critical',
  // battery_low:     'low',
} as const;

// ── Sort order (lower = more urgent) ──────────────────────────────────────

export const SEVERITY_RANK: Record<Severity, number> = {
  critical: 0,
  high:     1,
  medium:   2,
  low:      3,
};

// ── Display helpers ────────────────────────────────────────────────────────

export const SEVERITY_LABEL: Record<Severity, string> = {
  critical: 'Critical',
  high:     'High',
  medium:   'Medium',
  low:      'Low',
};

export const SEVERITY_STYLES: Record<Severity, {
  badge:  string;   // badge background + text
  border: string;   // left border on alert card
  banner: string;   // persistent banner background
}> = {
  critical: {
    badge:  'bg-red-100 text-red-700 border border-red-200',
    border: 'border-l-4 border-l-red-500',
    banner: 'bg-red-600',
  },
  high: {
    badge:  'bg-orange-100 text-orange-700 border border-orange-200',
    border: 'border-l-4 border-l-orange-500',
    banner: 'bg-orange-600',
  },
  medium: {
    badge:  'bg-amber-100 text-amber-700 border border-amber-200',
    border: 'border-l-4 border-l-amber-400',
    banner: 'bg-amber-600',
  },
  low: {
    badge:  'bg-green-100 text-green-700 border border-green-200',
    border: 'border-l-4 border-l-green-400',
    banner: 'bg-green-600',
  },
};

// ── Helper function ────────────────────────────────────────────────────────

/** Returns the severity for an event type. Defaults to 'low' for unknown types. */
export function getSeverity(type: string): Severity {
  return SEVERITY_MAP[type] ?? 'low';
}

/** Plain-language description of a notification. */
export function getAlertDescription(
  type: string,
  detail: Record<string, unknown> | null,
): string {
  switch (type) {
    case 'sos':
      return 'Patient pressed the help button.';
    case 'left_zone': {
      const dist = detail?.distance_m;
      return `Patient left the safe zone${dist ? ` — ${Number(dist).toLocaleString()} m from home` : ''}.`;
    }
    case 'inactivity':
      return "No activity detected from the patient's device.";
    case 'reminder_missed':
      return `Patient missed: ${String(detail?.title ?? 'a reminder')}.`;
    case 'reminder_done':
      return `Patient completed: ${String(detail?.title ?? 'a reminder')}.`;
    case 'companion_question':
      return `Patient asked the companion: "${String(detail?.question ?? '…')}"${detail?.deferred ? ' (could not answer)' : ''}.`;
    default:
      return type.replace(/_/g, ' ');
  }
}

export const ALERT_TYPE_LABEL: Record<string, string> = {
  sos:              'Help Requested',
  left_zone:        'Left Safe Zone',
  inactivity:       'Inactivity Alert',
  reminder_missed:  'Missed Reminder',
  reminder_done:    'Reminder Completed',
  companion_question: 'Companion Question',
};
